/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fo;

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Mostafa Salem
 */
public class FlightDetails extends javax.swing.JFrame {

    /**
     * Creates new form FlightDetails
     */
    public FlightDetails() {
        initComponents();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/pro","root","root");
            ///////////////////////////////////////////////////////////////////
            PreparedStatement d=c.prepareStatement("select A_Code from airlines");
            ResultSet res = d.executeQuery();
             while(res.next())
            {
                String pat = res.getString("A_Code");
                jComboBox4.addItem(pat);
            }
             
             
        } catch (SQLException ex) {
            Logger.getLogger(Airport_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Flight ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 50, 110, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Flight Class");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 110, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("From");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(11, 150, 110, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("To");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 150, 114, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Depart Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(11, 210, 110, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Depart Time");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 210, 110, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Arrive Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(11, 270, 100, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Arrive Time");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 270, 100, 24);

        jTextField1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 50, 160, 24);

        jComboBox1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Second Class", "Third Class", "Forth Class" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(130, 100, 100, 26);

        jComboBox2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(130, 150, 100, 26);

        jComboBox3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tokyo", "London", "Paris", "USA", "Dubai" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(480, 150, 80, 26);

        jComboBox5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00 am", "00:30 am", "01:00 am", "01:30 am", "02:00 am", "02:30 am", "03:00 am", "03:30 am", "04:00 am", "04:30 am", "05:00 am", "05:30 am", "06:00 am", "06:30 am", "07:00 am", "07:30 am", "08:00 am ", "08:30 am", "09:00 am", "09:30 am", "10:00 am", "10:30 am", "11:00 am", "11:30 am", "00:00 pm", "00:30 pm", "01:00 pm", "01:30 pm", "02:00 pm", "02:30 pm", "03:00 pm", "03:30 pm", "04:00 pm", "04:30 pm", "05:00 pm", "05:30 pm", "06:00 pm", "06:30 pm", "07:00 pm", "07:30 pm", "08:00 pm ", "08:30 pm", "09:00 pm", "09:30 pm", "10:00 pm", "10:30 pm", "11:00 pm", "11:30 pm", " " }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(480, 210, 86, 26);

        jComboBox12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00 am", "00:30 am", "01:00 am", "01:30 am", "02:00 am", "02:30 am", "03:00 am", "03:30 am", "04:00 am", "04:30 am", "05:00 am", "05:30 am", "06:00 am", "06:30 am", "07:00 am", "07:30 am", "08:00 am ", "08:30 am", "09:00 am", "09:30 am", "10:00 am", "10:30 am", "11:00 am", "11:30 am", "00:00 pm", "00:30 pm", "01:00 pm", "01:30 pm", "02:00 pm", "02:30 pm", "03:00 pm", "03:30 pm", "04:00 pm", "04:30 pm", "05:00 pm", "05:30 pm", "06:00 pm", "06:30 pm", "07:00 pm", "07:30 pm", "08:00 pm ", "08:30 pm", "09:00 pm", "09:30 pm", "10:00 pm", "10:30 pm", "11:00 pm", "11:30 pm", " " }));
        getContentPane().add(jComboBox12);
        jComboBox12.setBounds(480, 270, 86, 26);

        jButton2.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 340, 104, 35);

        jButton3.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 340, 107, 35);

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("Seat No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 100, 80, 24);

        jComboBox15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(jComboBox15);
        jComboBox15.setBounds(480, 100, 80, 26);

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Flight Details");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(230, 10, 230, 30);

        jXDatePicker2.setBackground(java.awt.SystemColor.activeCaptionBorder);
        getContentPane().add(jXDatePicker2);
        jXDatePicker2.setBounds(130, 270, 139, 24);

        jXDatePicker3.setBackground(java.awt.SystemColor.activeCaptionBorder);
        getContentPane().add(jXDatePicker3);
        jXDatePicker3.setBounds(130, 210, 139, 24);

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Airline");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 340, 90, 24);

        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(130, 340, 60, 26);
        getContentPane().add(jl);
        jl.setBounds(0, 0, 670, 390);

        setSize(new java.awt.Dimension(686, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       main r = new main();
       this.setVisible(false);
       r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String FCode=jTextField1.getText();
       String Class=(String) jComboBox1.getSelectedItem();
       String seatsNo =(String) jComboBox15.getSelectedItem();
       String FlyFrom =(String) jComboBox2.getSelectedItem();
       String FlyTo =(String) jComboBox3.getSelectedItem();
       
       DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       jXDatePicker1.setFormats(dateFormat);
       DateFormat sysDate = new SimpleDateFormat("dd/MM/yyyy");
       String date_to_store1 = sysDate.format(jXDatePicker3.getDate()).toString();
       String date_to_store2 = sysDate.format(jXDatePicker2.getDate()).toString();
      
       
       String dept_time =(String) jComboBox5.getSelectedItem();
       String arr_time =(String) jComboBox12.getSelectedItem();
       
       String airline =(String) jComboBox4.getSelectedItem();
        try {
            Connection c =DriverManager.getConnection("jdbc:mysql://localhost:3306/pro","root","root");
            PreparedStatement d =c.prepareStatement("insert into flight (Flight_No,Class,seatNo,FlyFrom,FlyTo,"
                    + "Dep_Date,Arr_Date,Dep_Time,Arr_Time,A_Code) values (?,?,?,?,?,?,?,?,?,?)");      
            d.setString(1,FCode);
            d.setString(2,Class);
            d.setString(3,seatsNo);
            d.setString(4,FlyFrom);
            d.setString(5,FlyTo);
            d.setString(6,date_to_store1);
            d.setString(7,date_to_store2);
            d.setString(8,dept_time);
            d.setString(9,arr_time);
           
            d.setString(10,airline);
            
            d.executeUpdate();    
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Airport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        try { 
            ImageIcon img = new ImageIcon(ImageIO.read(getClass().getResource("f13.jpg")).getScaledInstance(670,390, Image.SCALE_AREA_AVERAGING));
           jl.setIcon(img);
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private javax.swing.JLabel jl;
    // End of variables declaration//GEN-END:variables
}
