/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fo;

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Mostafa Salem
 */
public class NewAirplane extends javax.swing.JFrame {

    /**
     * Creates new form NewAirplane
     */
    public NewAirplane() {
        initComponents();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/pro","root","root");
            ///////////////////////////////////////////////////////////////////
            PreparedStatement d=c.prepareStatement("select A_Code from airlines");
            ResultSet res = d.executeQuery();
             while(res.next())
            {
                String pat = res.getString("A_Code");
                jComboBox4.addItem(pat);
            }
             //////////////////////////////////////////////////////////////////
            PreparedStatement d2=c.prepareStatement("select Port_Code from airport");
            res = d2.executeQuery();
             while(res.next())
            {
                String pat = res.getString("Port_Code");
                jComboBox5.addItem(pat);
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(Airport_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Airplane");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 150, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Registeration No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 75, 150, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("Airplane Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 139, 130, 24);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "738", "320", "321", "319", "737" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(250, 70, 60, 26);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boeing 737-800", "Airbus A320", "Airbus A321", "Airbus A319", "Boeing 737-700" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(250, 140, 118, 26);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Seats Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 203, 130, 24);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "25", "30", "35", "40" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 200, 60, 26);

        jButton1.setBackground(java.awt.SystemColor.controlShadow);
        jButton1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(251, 380, 120, 40);

        jButton2.setBackground(java.awt.SystemColor.controlShadow);
        jButton2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 380, 120, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Owned By Airline (Code)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 332, 220, 24);

        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(250, 330, 60, 26);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Travelling airport");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(23, 264, 160, 24);

        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(250, 260, 60, 26);
        getContentPane().add(jl);
        jl.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(416, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       main m = new main();
       this.setVisible(false);
       m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String planeCode=(String) jComboBox1.getSelectedItem();
       String Type=(String) jComboBox2.getSelectedItem();
       String seats=(String) jComboBox3.getSelectedItem();
       String line=(String) jComboBox4.getSelectedItem();
       try {
            Connection c =DriverManager.getConnection("jdbc:mysql://localhost:3306/pro","root","root");
            PreparedStatement d =c.prepareStatement("insert into airplane (Reg_No,Airplane_Type,Seats_Num,A_Code) "
                    + " values (?,?,?,?)");      
            d.setString(1,planeCode);
            d.setString(2,Type);
            d.setString(3,seats);
            d.setString(4,line);  
            d.executeUpdate();   
            
            
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        String port=(String) jComboBox5.getSelectedItem();
           PreparedStatement d2=c.prepareStatement("insert into lands_on (Reg_No,Port_Code) values (?,?)");
           d2.setString(1,planeCode);
           d2.setString(2,port);
           d2.executeUpdate();
           
        } catch (SQLException ex) {
            Logger.getLogger(Airport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        try { 
            ImageIcon img = new ImageIcon(ImageIO.read(getClass().getResource("f25.jpg")).getScaledInstance(400,450, Image.SCALE_AREA_AVERAGING));
           jl.setIcon(img);
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAirplane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAirplane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAirplane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAirplane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAirplane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jl;
    // End of variables declaration//GEN-END:variables
}
